version: '3.8'

services:
  server:
    build: .
    container_name: kodikos-api-express
    ports:
      - 3232:3232
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
    -  PORT=3232
    - DATABASE_URL="postgresql://postgres:password@localhost:5433/kodikosdb"
    - BCRYPT_SALT_ROUNDS=5
    - JWT_SECRET="your-secret-key"
    - JWT_EXPIRES_IN="30d"
    - ALLOWED_ORIGINS="http://localhost:8081"
    - SECURE=false

    restart: always
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: kodikos-db-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kodikosdb
    ports:
      - 5433:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: 